# Generated by Django 4.2.25 on 2025-11-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short name of the item, e.g. 'PS5 Controller'.", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Details, color, size, notes.')),
                ('link', models.URLField(blank=True, help_text='Optional link to buy this item.', max_length=500)),
                ('price_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Approx price or budget for this item (e.g. 29.99).', max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional photo / screenshot of the item.', null=True, upload_to='wishlist/')),
                ('is_claimed', models.BooleanField(default=False, help_text='Someone said they plan to buy this.')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('is_purchased', models.BooleanField(default=False, help_text='Item has been purchased.')),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, help_text='Which profile claimed this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_made', to='accounts.profile')),
                ('profile', models.ForeignKey(help_text='This item is wanted by this profile (the gift receiver).', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='accounts.profile')),
                ('purchased_by', models.ForeignKey(blank=True, help_text='Which profile bought this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_made', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
