# Generated by Django 4.2.25 on 2025-10-26 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child')], max_length=10)),
                ('avatar_choice', models.CharField(blank=True, help_text='Name/key of a preloaded avatar image.', max_length=255)),
                ('avatar_upload', models.ImageField(blank=True, help_text='User-uploaded avatar image.', null=True, upload_to='avatars/')),
                ('birthday', models.DateField()),
                ('anniversary', models.DateField(blank=True, help_text='Optional anniversary date.', null=True)),
                ('shirt_size', models.CharField(blank=True, max_length=50)),
                ('pants_size', models.CharField(blank=True, max_length=50)),
                ('shoe_size', models.CharField(blank=True, max_length=50)),
                ('hobbies_sports', models.TextField(blank=True)),
                ('favorite_stores', models.TextField(blank=True)),
                ('favorite_websites', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True, help_text='Visible only to Parent users in the UI.')),
                ('is_approved', models.BooleanField(default=False, help_text='Must be true before this user can access the full app.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
