# Generated by Django 4.2.25 on 2025-11-24 23:00

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent1', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_as_parent1', to=settings.AUTH_USER_MODEL)),
                ('parent2', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_as_parent2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Parent', 'Parent'), ('Child', 'Child')], max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('avatar_source', models.CharField(choices=[('default', 'Default'), ('library', 'Library'), ('upload', 'Upload')], default='default', max_length=20)),
                ('avatar_library_filename', models.CharField(blank=True, max_length=255)),
                ('avatar_upload', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_upload_path)),
                ('shirt_size', models.CharField(blank=True, max_length=50)),
                ('pants_size', models.CharField(blank=True, max_length=50)),
                ('shoe_size', models.CharField(blank=True, max_length=50)),
                ('hobbies_sports', models.TextField(blank=True)),
                ('favorite_stores', models.TextField(blank=True)),
                ('favorite_websites', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('parent1', models.F('parent2')), _negated=True), ('parent1__isnull', True), ('parent2__isnull', True), _connector='OR'), name='family_parent1_not_equal_parent2_or_null'),
        ),
    ]
