# Generated by Django 4.2.25 on 2025-10-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
    ]
