# Generated by Django 4.2.25 on 2025-10-27 20:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_family_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_library_filename',
            field=models.CharField(blank=True, help_text="Filename of a static avatar in static/images/avatars/users/, e.g. 'avatar_12.png'. Only used if avatar_source='library'.", max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_source',
            field=models.CharField(choices=[('default', 'Default'), ('library', 'Library Choice'), ('upload', 'Uploaded Image')], default='default', help_text="Where this profile's avatar comes from: default_user.png, one of the stock library avatars, or a custom upload.", max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_upload',
            field=models.ImageField(blank=True, help_text="User-uploaded avatar stored in media/avatars/users/. Only used if avatar_source='upload'.", null=True, upload_to=accounts.models.user_avatar_upload_path),
        ),
    ]
