# Generated by Django 4.2.25 on 2025-10-28 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['display_name'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.RemoveField(
            model_name='family',
            name='name',
        ),
        migrations.AddField(
            model_name='family',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='family',
            name='parent1',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Parent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_as_parent1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='parent2',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Parent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_as_parent2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.family'),
        ),
    ]
