# Generated by Django 4.2.26 on 2025-11-13 17:44

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_family_options_remove_family_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__first_name', 'user__last_name', 'user__username']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_choice',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='family',
            name='parent1',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_as_parent1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='family',
            name='parent2',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_as_parent2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_library_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_source',
            field=models.CharField(choices=[('default', 'Default'), ('library', 'Library'), ('upload', 'Upload')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_upload',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='private_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Parent', 'Parent'), ('Child', 'Child')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('parent1', models.F('parent2')), _negated=True), ('parent1__isnull', True), ('parent2__isnull', True), _connector='OR'), name='family_parent1_not_equal_parent2_or_null'),
        ),
    ]
